For Footer and buttons in mobile view is been set , so that they dont conjest .
PySangamam/website pull request #17
Opened 2018-05-02 11:59 UTC by syedjafer

For Footer and buttons in mobile view is been set , so that they dont conjest .

2018-05-02 14:38 UTC, astronomersiva commented on _includes/head.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
Can you fetch only the required fonts? Maybe even svgs from somewhere is fine. Let's not fetch the entire font-awesome library here

2018-05-02 14:38 UTC, astronomersiva commented on css/pysangamam.css
> +  padding-top: 0 !important;
Can you try and see if `!important` can be removed from all these styles?

2018-05-02 14:38 UTC, astronomersiva requested changes

2018-05-02 14:38 UTC, astronomersiva commented on css/pysangamam.css
> +  border-bottom: 20px solid #218c74;
15px is what we use everywhere for this bottom border.

2018-05-02 17:52 UTC, astronomersiva commented on _includes/footer.html
> +					<p>Brought to you by<a class="ml-2" href="https://chennaipy.org">Chennaipy .</a> Text is available under the<a class="ml-2" href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank"
Chennaipy . - There shouldn't be a space between Chennaipy and the full stop.

2018-05-03 03:24 UTC, astronomersiva commented on index.html
> +{% include footer.html %}
Can you add this to the default and page templates instead of here? That way, all pages that use that template will have the footer.

2018-05-03 12:44 UTC, syedjafer commented on index.html
> +{% include footer.html %}
:thumbsup:

2018-05-03 13:32 UTC, astronomersiva approved these changes

2018-05-03 13:33 UTC, merged

2018-05-03 13:33 UTC, astronomersiva commented
@syedjafer Thanks a lot for this 🎉