meta tags added
PySangamam/website pull request #32
Opened 2018-05-08 14:10 UTC by ragupathis

Meta tags for link preview added here,

Python logo used as a placeholder.

2018-05-08 15:32 UTC, astronomersiva requested changes

2018-05-08 15:32 UTC, astronomersiva commented on _includes/head.html
> +    <meta property="og:title" content="PySangamam - Tamil Nadu's first Python conference" />
I guess this can be in title case. `Tamil Nadu's First Python Conference`

2018-05-08 15:32 UTC, astronomersiva commented on _includes/head.html
> +    <meta property="og:description" content="September 7th and 8th, 2018 IC & SR - IIT Madras " />
The space after Madras can be removed.

2018-05-08 15:32 UTC, astronomersiva commented on _includes/head.html
> +    <meta property="og:url" content="http://pysangamam.org/" />
@shrayasr Did you look into that HTTPS fix? If that is done, we can change this to https

2018-05-08 15:32 UTC, astronomersiva commented on _includes/head.html
> +    <meta property="og:image" content="img/python_logo.png" />
It's a convention to have hyphenated file names in website assets.

2018-05-08 15:32 UTC, astronomersiva commented on _includes/head.html
> +    <meta name="description" content="PySangamam - Tamil Nadu's first Python conference - September 7th and 8th, 2018 IC & SR - IIT Madras" />
Title case here also.

2018-05-08 15:32 UTC, astronomersiva commented on _includes/head.html
> +    <meta name="keywords" content="PySangamam, Python, ChennaiPy" />
Can we add 'Conference' to this?

2018-05-09 04:19 UTC, astronomersiva commented on _includes/head.html
> +    <meta property="og:title" content="PySangamam - Tamil Nadu's first Python conference" />
@shrayasr ping 🔔

2018-05-09 12:25 UTC, ragupathis commented on _includes/head.html
> +    <meta name="keywords" content="PySangamam, Python, ChennaiPy" />
Added

2018-05-09 15:48 UTC, astronomersiva approved these changes

2018-05-09 15:49 UTC, merged

2018-05-09 15:49 UTC, astronomersiva commented
Awesome work @ragupathis !