Twitter Feed Added
PySangamam/website pull request #6
Opened 2018-04-26 16:33 UTC by syedjafer

Twiiter Feed is been Added to the site .

2018-04-26 17:01 UTC, astronomersiva commented
Hi @syedjafer, Thanks a ton for working on this!

Here are few suggestions:

* The files seem to have been copied to a `website` folder. You may want to move them back to root. That is, `index.html` is now in `website/index.html` in this branch.
*  I guess we can do away with `PySangamam Tweets` in this section. It looks redundant.
<img width="560" alt="screen shot 2018-04-26 at 10 22 19 pm" src="https://user-images.githubusercontent.com/7725225/39320037-8e088678-49a0-11e8-9c88-aa67f868fa2f.png">

* I personally feel that the Twitter Roll can be a bit taller. Long tweets will get cut off in this(especially if they have images).
* I really love how you have worked on the selection color. Takes an eye to detail to work on such things :) You might want to consider changing the color for `Py` alone in `PySangamam`. Please refer the image below.
<img width="221" alt="screen shot 2018-04-26 at 10 27 16 pm" src="https://user-images.githubusercontent.com/7725225/39320275-3b16dcde-49a1-11e8-8718-7f9aa5e674b2.png">

* I am not sure if this is happening because of some styles that we are applying but green text on blue background in the "Load More Tweets" button looks a bit odd.
<img width="213" alt="screen shot 2018-04-26 at 10 29 23 pm" src="https://user-images.githubusercontent.com/7725225/39320329-5e9e191a-49a1-11e8-9b3e-7b7837f87115.png">


Also, I assume the space on the left is for the blog roll? Considering how that might take a few more days and we do not want to delay merging this till then, can you position this normally itself?

Cheers!

2018-04-26 17:04 UTC, astronomersiva requested changes

2018-04-26 17:04 UTC, astronomersiva commented on index.html
> +        <a class="twitter-timeline" data-width="500" data-height="300" data-theme="light" data-link-color="#19CF86" href="https://twitter.com/pysangamam?ref_src=twsrc%5Etfw">Tweets by PySangamam </a>
Nitpicking here but this indentation looks a bit off.

2018-04-26 17:04 UTC, astronomersiva commented on index.html
> +
Can you please remove all these empty lines?

2018-04-26 17:04 UTC, astronomersiva commented on website/CNAME
> +pysangamam.org
It looks like all contents have been moved to `website` folder. Please check this.

2018-04-27 19:14 UTC, astronomersiva commented
Hi @syedjafer , please go through [these comments](https://github.com/PySangamam/website/pull/6#issuecomment-384715347). I can still see the orange-ish selection color for Py in PySangamam. The "Load More Tweets" button can have white text when hovered.

2018-04-27 19:17 UTC, astronomersiva requested changes

2018-04-27 19:17 UTC, astronomersiva commented on index.html
> +          <h2 class="text-center"><b id="Py">Py</b> <b id="Sangamam">Sangamam</b> Tweets </h2>
We can remove this header. It is redundant.

2018-04-27 19:17 UTC, astronomersiva commented on index.html
> +        <a class="twitter-timeline" data-width="600" data-height="400" data-theme="light" data-link-color="#2B7BB9" href="https://twitter.com/pysangamam?ref_src=twsrc%5Etfw">Tweets by PySangamam </a>
Please remove the `?ref_src=twsrc%5Etfw` from the URL..

2018-04-27 19:17 UTC, astronomersiva commented on index.html
> +
I guess we can remove these blank lines too.

2018-04-29 08:49 UTC, astronomersiva commented
Please remove the footer and push. I will merge the Twitter changes now and we can have the footer as a separate PR.

2018-04-29 12:30 UTC, astronomersiva commented
@syedjafer sorry for nagging..but there seems to be merge conflicts :/

2018-04-29 13:59 UTC, syedjafer commented
It works , http://syedjafer.me/website/

2018-04-29 14:22 UTC, astronomersiva approved these changes

2018-04-29 14:23 UTC, merged

2018-04-29 14:23 UTC, astronomersiva commented
Thanks for working on this @syedjafer 🥇

2018-04-29 15:22 UTC, syedjafer commented
Its my pleasure @astronomersiva

2018-04-29 15:24 UTC, syedjafer commented
About Footer ?